INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Gryffindor');
INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Ravenclaw');
INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Slytherin');
INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Gryffindor');
INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Gryffindor');
INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Gryffindor');
INSERT INTO RESULTADO(NOMBRE,CASA_FINAL) values('Alex','Gryffindor');